"Reproducible Research: Peer Assessment 1"
---------------------------------------------------

```{r}
# load required packages
library(knitr)
library(dplyr)
library(ggplot2)

# set echo = TRUE
opts_chunk$set(echo = TRUE)

# set up working directory
setwd("~/DataScientist/Reproducible Research/RepData_PeerAssessment1")

# load data

data_file <- read.csv('activity.csv')

# remove NA in data
data <- data_file[ with (data_file, { !(is.na(steps)) } ), ]

# review first 10 rows and structure 
head(data,10)
str(data)

# What is mean total number of steps taken per day?
by_day <- group_by(data, date)
steps_by_day <- summarise(by_day, total = sum(steps))

# Histogram of mean total number of steps taken per day
hist(steps_by_day$total, main="Histogram of total number of steps per day", 
     xlab="Total number of steps in a day")

summary(steps_by_day)
```
The mean of total number of steps is 10766, median is 10765
```{r}
# What is the average daily activity pattern?
## Make a time series plot 
## Which 5-minute interval contains the maximum number of steps?

# Preprocessing data for plot
steps_by_interval <- aggregate(steps ~ interval, data, mean)

# create a time series plot 
plot(steps_by_interval$interval, steps_by_interval$steps, type='l', 
     main="Average number of steps over all days", xlab="Interval", 
     ylab="Average number of steps")

# find row with max of steps
max_steps_row <- which.max(steps_by_interval$steps)

# find interval with this max
steps_by_interval[max_steps_row, ]

#Imputing missing values

## Calculate the total number of missing values in the dataset
sum(is.na(data_file))

## Devise a strategy for filling in all of the missing values in the dataset
## Create a new dataset equal to the original but with the missing data filled in

data_imputed <- data_file
for (i in 1:nrow(data_imputed)) {
  if (is.na(data_imputed$steps[i])) {
    interval_value <- data_imputed$interval[i]
    steps_value <- steps_by_interval[
      steps_by_interval$interval == interval_value,]
    data_imputed$steps[i] <- steps_value$steps
  }
}
```
Imputation strategy of replacing NA's with the mean for that 5 minute interval
```{r}
# calculate  total number of steps taken each day
df_imputed_steps_by_day <- aggregate(steps ~ date, data_imputed, sum)
head(df_imputed_steps_by_day)

## Make a histogram of the total number of steps taken each day 

hist(df_imputed_steps_by_day$steps, main="Histogram of total number of steps per day (imputed)", 
     xlab="Total number of steps in a day")

## Calculate the mean and median total number of steps taken per day
mean(df_imputed_steps_by_day$steps)
median(df_imputed_steps_by_day$steps)

## Do these values differ from the estimates from first part of the assignment?
## What is the impact of imputing missing data on the estimates?
mean(steps_by_day$total)
median(steps_by_day$total)
```
Mean value stays the same but there is a small difference in median value
```{r}
# Are there differences in activity patterns between weekdays and weekends?

## For this part the weekdays() function may be of some help here. Use the dataset with the filled-in missing values for this part.
## Create a new factor variable in the dataset with two levels - "weekday" and "weekend" indicating whether a given date is a weekday or weekend day.

data_imputed['type_of_day'] <- weekdays(as.Date(data_imputed$date))

data_imputed$type_of_day[data_imputed$type_of_day  %in% c('Saturday','Sunday') ] <- "weekend"
data_imputed$type_of_day[data_imputed$type_of_day != "weekend"] <- "weekday"

# convert type_of_day from character to factor
data_imputed$type_of_day <- as.factor(data_imputed$type_of_day)

# calculate average steps by interval across all days
df_imputed_steps_by_interval <- aggregate(steps ~ interval + type_of_day, data_imputed, mean)

# Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). 

qplot(interval, 
      steps, 
      data = df_imputed_steps_by_interval, 
      type = 'l', 
      geom=c("line"),
      xlab = "Interval", 
      ylab = "Number of steps", 
      main = "") +
  facet_wrap(~ type_of_day, ncol = 1)
```
